### ISSUE TITLE
Contact Merge Issue

### ISSUE THREAD

**Issue by mcp79** [kyleschmid/ObjectMerge#25]
I have followed the instructions and I am not able to get this working for merging contact records.
When I create the Contact as the parent and then use the account as the child "Object Handler Not Found"

I have tried Creating the Account as the Parent and the Contact as the child. Then when I try to merge records I get "Error Performing DML".

I have tried creating the Contact Only as the Parent record with no related children. Then when I try to merge two contact records, I get a query error"

To make this happen what is the parent and what is child to merge to duplicate contact records?

**Comment by mcp79** [comment]
@kyleschmid Any guidance here would be awesome, I have spent a ton of timing trying different handler combinations to get this to merge two duplicate contact records.

**Comment by kyleschmid** [comment]
@mcp79 Take a look at the videos below. They are linked on the [ObjectMerge PowerOfUs](https://powerofus.force.com/s/group/0F980000000LjqFCAS/objectmerge) hub group.

1. [About Object Merge](https://powerofus.force.com/0691E000002dcXM) (6:14): Video giving a short overview
2. [Install Object Merge](https://powerofus.force.com/0691E000002dcXR) (0:34): Video showing how to install
3. [Setup Object Merge](https://powerofus.force.com/0691E000002dcXW) (18:58): Video showing how to setup/configure
4. [No More Duplicates With ObjectMerge!](https://powerofus.force.com/s/files/0691E000004XkyIQAS): Slide deck used during the ObjectMerge workshop at Higher-Ed Summit 2019. Shows installation, configuration, and examples.

**Comment by mcp79** [comment]
Awesome! Thank you Kyle!!!

Maria Phipps
Salesforce - Contractor
University of Pittsburgh | CSSD

________________________________

**Comment by mcp79** [comment]
@kyleschmid Not all the video's are working.
1. The first video, I can hear your voice but there is no video
2. This video is working fine
3. This video is working fine
4. This is not a working video 
 takes you to th zoom link below https://hcg.zoom.us/recording/play/FhIDkyS73udWjpap8dhHpHRssR2Q6HmB4fcclENKjwNT--JD4d7rtx53DbBu4Ru2?continueMode=true
there is no zoom recording or video.

**Comment by kyleschmid** [comment]
@mcp79 The first video is fixed now. Looks like the Zoom recording for the 4th video is no longer available. Unfortunately, I don't have it backed up anywhere. Just replaced the link with the slide deck used during the workshop instead.

**Comment by mcp79** [comment]
@kyleschmid Thank you for updating. I have completed all the configuration and I can't get this to work. I have attached a word document with all my steps....I have no clue what is going on as it seems pretty straight forward.
[Object Merge Still Not Working.docx](https://github.com/kyleschmid/ObjectMerge/files/4016827/Object.Merge.Still.Not.Working.docx)

**Comment by kyleschmid** [comment]
@mcp79 "Error running query" means there's an issue with one of the API names. Everything looks right in your screenshots from what I can see except the "MailingAddress" field on Contact. This should be split into the five fields that make it up (MailingStreet, MailingCity, etc.). One of your custom fields could also be wrong. To pinpoint the exact issue, you can open up the developer console and retry the merge. The resulting debug log will give you the actual apex error that occurred, which is more descriptive than the ObjectMerge error.

**Comment by mcp79** [comment]
@kyleschmid Thank you for your response. Taking in account what you asked me to try here is what I came up with:
1. For simplicity and not adding more fields to something that is not working, I removed "Mailing Address" from the configuration.
2. I did a retry on the objectmerge and had the developer console open. It threw what I believe to be the issue "17:01:56.209 (2239002631)|EXCEPTION_THROWN|[136]|System.QueryException: duplicate field selected: hed__Contact__c". When I research this error, This issue is occurring because there are two fields with the same name (one customer and one that is used by NPSP) - https://help.salesforce.com/articleView?id=000317472&type=1&mode=1.
I went into all the objects to search for a duplicate field and it doesn't exist.So is the issue because when I create the child handlers for Relationship and Affiliation in this field "Object Lookup Field API Name" I am specificing "hed__Contact__c" and then I reference it in the relationship handler as a field which I match for a duplicate.

Other Scenarios/Tests Run:

I ran was I removed the hed_contact_c in the relationship child handler as a matching field and re-ran the handler and I got a DML error 17:23:39.947 (3424103183)|DML_END|[274]
17:23:39.947 (3432562586)|EXCEPTION_THROWN|[277]|ObjectMergePairTriggerHandler.ObjectMergePairException: Script-thrown exception

If I deactivate all of the children handlers and assume I only want to merge contacts with no related objects I get a DML error.

If  deactivate the relationship child handler so I am only referencing HED__Contact__C in one child handler and a re-run the object merge, I get a DML error.

**Comment by kyleschmid** [comment]
@mcp79 You'll want to remove all Object Merge Fields that match the Object Lookup Field API Name of the corresponding handler. When you setup a child handler, the relationship to the parent is defined by what you specify in Object Lookup Field API Name. This field is added to the query by default, so when it's also specified as an Object Merge Field record, it gets duplicated.
